//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 05:00:31 PM IST 
//


package com.soaptest.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.blog.samples.webservices.accountservice.AccountDetailsResponse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountDetailsResponse" type="{http://com/blog/samples/webservices/accountservice}AccountDetailsResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountDetailsResponse"
})
@XmlRootElement(name = "createAccountResponse", namespace = "http://services.soaptest.com/")
public class CreateAccountResponse {

    protected AccountDetailsResponse accountDetailsResponse;

    /**
     * Gets the value of the accountDetailsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDetailsResponse }
     *     
     */
    public AccountDetailsResponse getAccountDetailsResponse() {
        return accountDetailsResponse;
    }

    /**
     * Sets the value of the accountDetailsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDetailsResponse }
     *     
     */
    public void setAccountDetailsResponse(AccountDetailsResponse value) {
        this.accountDetailsResponse = value;
    }

}
